#include "cbase.h"

#if GAME_DLL

//includes
#include "achievementmgr.h"
#include "baseachievement.h"

//achievement manager
extern CAchievementMgr g_AchievementMgrHL2;

//Find all the new alone mod locations
class CAchievementAloneModFindNewLocations : public CBaseAchievement
{
	virtual void Init()
	{
		static const char* szComponents[] =
		{
			"AMOD_NEW_LOCATIONS_STATION_TOCANROOM", "AMOD_NEW_LOCATIONS_STATION_TONPROSPEKT", "AMOD_NEW_LOCATIONS_STATION_SECURITY",
			"AMOD_NEW_LOCATIONS_PLAZA_OUTSIDE_NEW_APARTMENTS",
			"AMOD_NEW_LOCATIONS_APARTMENTS_RAID_ROOM", "AMOD_NEW_LOCATIONS_APARTMENTS_UPSTAIRS_ROOM",
			"AMOD_NEW_LOCATIONS_STATION_APARTMENTS_STREETS", "AMOD_NEW_LOCATIONS_STATION_STREET_STORAGE_ABOVE",
			"AMOD_NEW_LOCATIONS_KLAB_OUTSIDE_LADDER",
			"AMOD_NEW_LOCATIONS_CANALS_WAREHOUSE_NEXT_TO_STATION",
			"AMOD_NEW_LOCATIONS_CANALS_SEWERS_ABOVE",
			"AMOD_NEW_LOCATIONS_CANALS_RAILLINE",
			"AMOD_NEW_LOCATIONS_CANALS_VENT", "AMOD_NEW_LOCATIONS_CANALS_SEWERS_ABOVE2",
			"AMOD_NEW_LOCATIONS_CANALS_DAM", "AMOD_NEW_LOCATIONS_CANALS_BARN",
			"AMOD_NEW_LOCATIONS_CANALS_WAREHOUSE_CARGO_DECK", "AMOD_NEW_LOCATIONS_CANALS_WAREHOUSE_CARGO_STORAGE_DECK",
			"AMOD_NEW_LOCATIONS_CANALS_WAREHOUSE_OUTSIDE",
			"AMOD_NEW_LOCATIONS_CANALS_UNDER_HIGHWAY",
			"AMOD_NEW_LOCATIONS_CANALS_TRAINLINE", "AMOD_NEW_LOCATIONS_CANALS_WAREHOUSE_11",
			"AMOD_NEW_LOCATIONS_CANALS_WAREHOUSE_SIDE_OUTSIDE", "AMOD_NEW_LOCATIONS_CANALS_CARGO_DECK",
			"AMOD_NEW_LOCATIONS_ELI_LAB_ELECTRICITY_ROOM",
			"AMOD_NEW_LOCATIONS_TOWN_YARD",
			"AMOD_NEW_LOCATIONS_RAV_TO_COAST_WAREHOUSE", "AMOD_NEW_LOCATIONS_RAV_TO_COAST_WAREHOUSE_2", "AMOD_NEW_LOCATIONS_RAV_TO_COAST_TRAINLINE",
			"AMOD_NEW_LOCATIONS_COAST_DECK", "AMOD_NEW_LOCATIONS_COAST_DECK2",
			"AMOD_NEW_LOCATIONS_COAST_WAREHOUSE",
			"AMOD_NEW_LOCATIONS_PRISON_GUARD_ROOMS",
			"AMOD_NEW_LOCATIONS_PRISON_EZ2_SPOT",
			"AMOD_NEW_LOCATIONS_PRISON_HALLWAY",
			"AMOD_NEW_LOCATIONS_PRISON_BLOCKED_DOOR", "AMOD_NEW_LOCATIONS_PRISON_CELLS",
			"AMOD_NEW_LOCATIONS_PRISON_COMBINE_CELLS",
			"AMOD_NEW_LOCATIONS_C17_04_NEW_APARTMENTS", "AMOD_NEW_LOCATIONS_C17_04_NEW_EP1_APARTMENTS",
			"AMOD_NEW_LOCATIONS_C17_05_NEW_APARTMENTS_DOWNSTAIRS", "AMOD_NEW_LOCATIONS_C17_05_NEW_APARTMENTS_UPSTAIRS", "AMOD_NEW_LOCATIONS_C17_05_NEW_OFFICES",
			"AMOD_NEW_LOCATIONS_C17_06B_OUTSIDE",
			"AMOD_NEW_LOCATIONS_C17_07_BRIDGE", "AMOD_NEW_LOCATIONS_C17_07_SUBURBEN_BLOCK", "AMOD_NEW_LOCATIONS_C17_07_MEETING_ROOM",
			"AMOD_NEW_LOCATIONS_C17_09_TO_07_CONTINUITY",
			"AMOD_NEW_LOCATIONS_C17_10A_CITY_STREET",
			"AMOD_NEW_LOCATIONS_C17_13_STREET",
		};

		SetFlags(ACH_HAS_COMPONENTS | ACH_LISTEN_COMPONENT_EVENTS | ACH_SAVE_GLOBAL);
		m_pszComponentNames = szComponents;
		m_iNumComponents = ARRAYSIZE(szComponents);
		SetComponentPrefix("AMOD_NEW_LOCATIONS");
		SetGoal(m_iNumComponents);
	}
}; 
DECLARE_ACHIEVEMENT(CAchievementAloneModFindNewLocations, ACHIEVEMENT_AMOD_FIND_NEWLOCATIONS, "AMOD_FIND_NEWLOCATIONS", 15);

//press all of the buttons on the portal maps
class CAchievementAloneModPortalMapsPressAllButtons : public CBaseAchievement
{
	virtual void Init()
	{
		static const char* szComponents[] =
		{
			"AMOD_PORTAL_PRESS_ALL_BUTTONS_BUTTON_PORTAL2_06",
			"AMOD_PORTAL_PRESS_ALL_BUTTONS_BUTTON_PORTAL1_04",
			"AMOD_PORTAL_PRESS_ALL_BUTTONS_BUTTON_PORTAL1_16",
			"AMOD_PORTAL_PRESS_ALL_BUTTONS_BUTTON_PORTAL1_01",
			"AMOD_PORTAL_PRESS_ALL_BUTTONS_BUTTON_PORTAL1_14",
			"AMOD_PORTAL_PRESS_ALL_BUTTONS_BUTTON_PORTAL1_09",
			"AMOD_PORTAL_PRESS_ALL_BUTTONS_BUTTON_PORTAL1_12",
		};

		SetFlags(ACH_HAS_COMPONENTS | ACH_LISTEN_COMPONENT_EVENTS | ACH_SAVE_GLOBAL);
		m_pszComponentNames = szComponents;
		m_iNumComponents = ARRAYSIZE(szComponents);
		SetComponentPrefix("AMOD_PORTAL_PRESS_ALL_BUTTONS");
		SetGoal(m_iNumComponents);
		SetHideUntilAchieved(true);
	}
};
DECLARE_ACHIEVEMENT(CAchievementAloneModPortalMapsPressAllButtons, ACHIEVEMENT_AMOD_PORTAL_PRESS_ALL_BUTTONS, "AMOD_PORTAL_PRESS_ALL_BUTTONS", 10);

//Find the portal facility
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_AMOD_FIND_PORTAL, "AMOD_PORTAL_FACILITY", 5);

#endif