#include "shaderlib/cshader.h"
class clouds_volumetric_ps30_Static_Index
{
public:
	clouds_volumetric_ps30_Static_Index( )
	{
	}
	int GetIndex()
	{
		// Asserts to make sure that we aren't using any skipped combinations.
		// Asserts to make sure that we are setting all of the combination vars.
#ifdef _DEBUG
#endif // _DEBUG
		return 0;
	}
};
#define shaderStaticTest_clouds_volumetric_ps30 0
class clouds_volumetric_ps30_Dynamic_Index
{
public:
	clouds_volumetric_ps30_Dynamic_Index()
	{
	}
	int GetIndex()
	{
		// Asserts to make sure that we aren't using any skipped combinations.
		// Asserts to make sure that we are setting all of the combination vars.
#ifdef _DEBUG
#endif // _DEBUG
		return 0;
	}
};
#define shaderDynamicTest_clouds_volumetric_ps30 0
