default:  fxctmp9_tmp\vertexlit_and_unlit_generic_bump_ps30.inc shaders\fxc\vertexlit_and_unlit_generic_bump_ps30.vcs fxctmp9_tmp\vertexlit_and_unlit_generic_bump_vs30.inc shaders\fxc\vertexlit_and_unlit_generic_bump_vs30.vcs fxctmp9_tmp\vertexlit_and_unlit_generic_ps30.inc shaders\fxc\vertexlit_and_unlit_generic_ps30.vcs fxctmp9_tmp\vertexlit_and_unlit_generic_vs30.inc shaders\fxc\vertexlit_and_unlit_generic_vs30.vcs

fxctmp9_tmp\vertexlit_and_unlit_generic_bump_ps30.inc shaders\fxc\vertexlit_and_unlit_generic_bump_ps30.vcs: vertexlit_and_unlit_generic_bump_ps2x.fxc common_pragmas.h common_flashlight_fxc.h common_hlsl_cpp_consts.h common_fxc.h common_ps_fxc.h common_vertexlitgeneric_dx9.h
	perl ..\..\devtools\bin\fxc_prep.pl   -source "..\.." vertexlit_and_unlit_generic_bump_ps2x.fxc-----vertexlit_and_unlit_generic_bump_ps30
	echo vertexlit_and_unlit_generic_bump_ps2x.fxc>> filestocopy.txt
	echo common_pragmas.h>> filestocopy.txt
	echo common_flashlight_fxc.h>> filestocopy.txt
	echo common_hlsl_cpp_consts.h>> filestocopy.txt
	echo common_fxc.h>> filestocopy.txt
	echo common_ps_fxc.h>> filestocopy.txt
	echo common_vertexlitgeneric_dx9.h>> filestocopy.txt

fxctmp9_tmp\vertexlit_and_unlit_generic_bump_vs30.inc shaders\fxc\vertexlit_and_unlit_generic_bump_vs30.vcs: vertexlit_and_unlit_generic_bump_vs20.fxc common_fxc.h common_hlsl_cpp_consts.h common_pragmas.h common_vs_fxc.h
	perl ..\..\devtools\bin\fxc_prep.pl   -source "..\.." vertexlit_and_unlit_generic_bump_vs20.fxc-----vertexlit_and_unlit_generic_bump_vs30
	echo vertexlit_and_unlit_generic_bump_vs20.fxc>> filestocopy.txt
	echo common_fxc.h>> filestocopy.txt
	echo common_hlsl_cpp_consts.h>> filestocopy.txt
	echo common_pragmas.h>> filestocopy.txt
	echo common_vs_fxc.h>> filestocopy.txt

fxctmp9_tmp\vertexlit_and_unlit_generic_ps30.inc shaders\fxc\vertexlit_and_unlit_generic_ps30.vcs: vertexlit_and_unlit_generic_ps2x.fxc common_vertexlitgeneric_dx9.h common_fxc.h common_hlsl_cpp_consts.h common_ps_fxc.h common_flashlight_fxc.h common_pragmas.h
	perl ..\..\devtools\bin\fxc_prep.pl   -source "..\.." vertexlit_and_unlit_generic_ps2x.fxc-----vertexlit_and_unlit_generic_ps30
	echo vertexlit_and_unlit_generic_ps2x.fxc>> filestocopy.txt
	echo common_vertexlitgeneric_dx9.h>> filestocopy.txt
	echo common_fxc.h>> filestocopy.txt
	echo common_hlsl_cpp_consts.h>> filestocopy.txt
	echo common_ps_fxc.h>> filestocopy.txt
	echo common_flashlight_fxc.h>> filestocopy.txt
	echo common_pragmas.h>> filestocopy.txt

fxctmp9_tmp\vertexlit_and_unlit_generic_vs30.inc shaders\fxc\vertexlit_and_unlit_generic_vs30.vcs: vertexlit_and_unlit_generic_vs20.fxc common_vs_fxc.h common_hlsl_cpp_consts.h common_fxc.h common_pragmas.h
	perl ..\..\devtools\bin\fxc_prep.pl   -source "..\.." vertexlit_and_unlit_generic_vs20.fxc-----vertexlit_and_unlit_generic_vs30
	echo vertexlit_and_unlit_generic_vs20.fxc>> filestocopy.txt
	echo common_vs_fxc.h>> filestocopy.txt
	echo common_hlsl_cpp_consts.h>> filestocopy.txt
	echo common_fxc.h>> filestocopy.txt
	echo common_pragmas.h>> filestocopy.txt

